### ISSUE TITLE
【0415】千葉県_感染者発生状況.xlsxの変換時に時間がかかり警告も出ます。

### ISSUE THREAD

**Issue by AstroTaka** [civictechzenchiba/covid19-chiba-tools#12]
「【0413】千葉県_感染者発生状況.xlsx」はファイルサイズが39kで処理時間はCeleron J4105のUbuntu 20.04で2,3秒でしたが
「【0415】千葉県_感染者発生状況.xlsx」はファイルサイズが1147kで処理時間は70秒ほどかかるようになりました。
Excelで"0415"を開いて印刷範囲外のK列からXDY列まで選択して削除して保存したところ
ファイルサイズが50kになり処理時間は2,3秒となりました。

また"0415"は以下の警告が出るようになりましたがExcelのドキュメント検査を行いフッターが検知されるので削除をして保存したところ警告も出ず"0413"と同じ挙動となりました。

```
 UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
```

**Comment by MiyukiShirasawa** [comment]
今日、最新ので再度確認してみます。

**Comment by AstroTaka** [comment]
よろしくお願いします。

**Comment by MiyukiShirasawa** [comment]
本日のファイルでは解消したみたいですー！

**Comment by AstroTaka** [comment]
ありがとうございます！
