### ISSUE TITLE
SSLCertVerificationError

### ISSUE THREAD

**Issue by MiyukiShirasawa** [civictechzenchiba/covid19-chiba-tools#7]
localで実行すると

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

というエラーが出てしまう

**Comment by 5ym** [comment]
問題なさそうであればクローズお願いします。

**Comment by smellman** [comment]
これって環境の問題だし、そもそも対応してはいけないっていう認識でした...

**Comment by 5ym** [comment]
旧バージョンはデフォルト未検証でした最新バージョンは検証の設定がいります一様`PROTOCOL_TLSv1_2`で検証を追加してもいいですがそこまでの保守性は不要と判断したので`_create_unverified_context`を指定して旧バージョンと同一の動作をするようにしています。

**Comment by smellman** [comment]
ふむ、了解です。
